chore: found snapshot
copying code from `vitest-plugin-vis`.
Else running into:

```
ReferenceError: exports is not defined
        at file:///home/runner/work/visual-testing/visual-testing/node_modules/.pnpm/type-plus@8.0.0-beta.7/node_modules/type-plus/cjs/index.js:16:23
```

caused by:
https://stackoverflow.com/questions/79335257/referenceerror-exports-is-not-defined-after-update-to-node-22-12-from-node-22